/*
 *
 * Agents constants
 *
 */

export const DEFAULT = 'app/Agents/';

export const TOGGLE_DIALOG = `${DEFAULT}TOGGLE_DIALOG`;

export const SAVE_AGENT = `${DEFAULT}SAVE_AGENT`;
export const SAVING_AGENT = `${DEFAULT}SAVING_AGENT`;
export const SAVING_AGENT_SUCCESS = `${DEFAULT}SAVING_AGENT_SUCCESS`;
export const SAVING_AGENT_FAILURE = `${DEFAULT}SAVING_AGENT_FAILURE`;

export const DELETE_AGENT = `${DEFAULT}DELETE_AGENT`;
export const DELETING_AGENT = `${DEFAULT}DELETING_AGENT`;
export const DELETING_AGENT_SUCCESS = `${DEFAULT}DELETING_AGENT_SUCCESS`;
export const DELETING_AGENT_FAILURE = `${DEFAULT}DELETING_AGENT_FAILURE`;

export const UPDATE_AGENT = `${DEFAULT}UPDATE_AGENT`;
export const UPDATE_AGENT_SUCCESS = `${DEFAULT}UPDATE_AGENT_SUCCESS`;

export const GET_AGENTS = `${DEFAULT}GET_AGENTS`;
export const GETTING_AGENTS = `${DEFAULT}GETTING_AGENTS`;
export const GETTING_AGENTS_SUCCESS = `${DEFAULT}GETTING_AGENTS_SUCCESS`;
export const GETTING_AGENTS_FAILURE = `${DEFAULT}GETTING_AGENTS_FAILURE`;
