/*
 *
 * Synonyms constants
 *
 */

export const DEFAULT = 'SynonymsE/';

export const GET_SYNONYMS = `${DEFAULT}GET_SYNONYMS`;
export const GETTING_SYNONYMS = `${DEFAULT}GETTING_SYNONYMS`;
export const GET_SYNONYMS_SUCCESS = `${DEFAULT}GET_SYNONYMS_SUCCESS`;
export const GET_SYNONYMS_FAILURE = `${DEFAULT}GET_SYNONYMS_FAILURE`;

export const UPDATE_VARIANTS = `${DEFAULT}UPDATE_VARIANTS`;
export const UPDATING_VARIANTS = `${DEFAULT}UPDATING_VARIANTS`;
export const UPDATE_VARIANTS_SUCCESS = `${DEFAULT}UPDAT_VARIANTS_SUCCESS`;
export const UPDATE_VARIANTS_FAILURE = `${DEFAULT}UPDATE_VARIANTS_FAILURE`;

export const ADD_SYNONYMS = `${DEFAULT}ADD_SYNONYMS`;
export const ADDING_SYNONYMS = `${DEFAULT}ADDING_SYNONYMS`;
export const ADD_SYNONYMS_SUCCESS = `${DEFAULT}ADD_SYNONYMS_SUCCESS`;
export const ADD_SYNONYMS_FAILURE = `${DEFAULT}ADD_SYNONYMS_FAILURE`;

export const REMOVE_SYNONYMS = `${DEFAULT}REMOVE_SYNONYMS`;
export const REMOVING_SYNONYMS = `${DEFAULT}REMOVING_SYNONYMS`;
export const REMOVE_SYNONYMS_SUCCESS = `${DEFAULT}REMOVE_SYNONYMS_SUCCESS`;
export const REMOVE_SYNONYMS_FAILURE = `${DEFAULT}REMOVE_SYNONYMS_FAILURE`;
