/*
 *
 * RightSidebar constants
 *
 */

export const DEFAULT = 'RightSidebar/';

export const UPDATE_AGENT = `${DEFAULT}UPDATE_AGENT`;
export const REMOVE_AGENT = `${DEFAULT}REMOVE_AGENT`;
export const UPDATE_MODEL = `${DEFAULT}UPDATE_MODEL`;
export const UPDATE_EXPRESSION = `${DEFAULT}UPDATE_EXPRESSION`;

export const GET_STATUS = `${DEFAULT}GET_STATUS`;
export const GETTING_STATUS = `${DEFAULT}GETTING_STATUS`;
export const GET_STATUS_SUCCESS = `${DEFAULT}GET_STATUS_SUCCESS`;
export const GET_STATUS_FAILURE = `${DEFAULT}GET_STATUS_FAILURE`;

export const SEND_QUERY = `${DEFAULT}SEND_QUERY`;
export const SENDING_QUERY = `${DEFAULT}SENDING_QUERY`;
export const SEND_QUERY_SUCCESS = `${DEFAULT}SEND_QUERY_SUCCESS`;
export const SEND_QUERY_FAILURE = `${DEFAULT}SEND_QUERY_FAILURE`;

export const SEND_CHAT = `${DEFAULT}SEND_CHAT`;
export const SENDING_CHAT = `${DEFAULT}SENDING_CHAT`;
export const SEND_CHAT_SUCCESS = `${DEFAULT}SEND_CHAT_SUCCESS`;
export const SEND_CHAT_FAILURE = `${DEFAULT}SEND_CHAT_FAILURE`;

export const RESET_CHAT = `${DEFAULT}RESET_CHAT`;
