/*
 *
 * SingleTalkFlow constants
 *
 */

export const DEFAULT_ACTION = 'app/SingleTalkFlow/DEFAULT_ACTION';
const DEFAULT = 'app/SingleTalkFlow/';

export const SET_PARENT_NODE = `${DEFAULT}SET_PARENT_NODE`;
export const SET_EDIT_UID = `${DEFAULT}SET_EDIT_UID`;

export const LOAD_NODE_FAMILY = `${DEFAULT}LOAD_NODE_FAMILY`;
export const REQUESTING_NODE_FAMILY = `${DEFAULT}REQUESTING_NODE_FAMILY`;
export const LOAD_NODE_FAMILY_SUCCESS = `${DEFAULT}LOAD_NODE_FAMILY_SUCCESS`;
export const LOAD_NODE_FAMILY_FAILURE = `${DEFAULT}LOAD_NODE_FAMILY_FAILURE`;

export const ADD_NODE = `${DEFAULT}ADD_NODE`;
export const ADDING_NODE = `${DEFAULT}ADDING_NODE`;
export const ADD_NODE_SUCCESS = `${DEFAULT}ADD_NODE_SUCCESS`;
export const ADD_NODE_FAILURE = `${DEFAULT}ADD_NODE_FAILURE`;

export const REMOVE_NODE = `${DEFAULT}REMOVE_NODE`;
export const REMOVING_NODE = `${DEFAULT}REMOVING_NODE`;
export const REMOVE_NODE_SUCCESS = `${DEFAULT}REMOVE_NODE_SUCCESS`;
export const REMOVE_NODE_FAILURE = `${DEFAULT}REMOVE_NODE_FAILURE`;

export const MOVE_NODE = `${DEFAULT}MOVE_NODE`;
export const MOVING_NODE = `${DEFAULT}MOVING_NODE`;
export const MOVE_NODE_SUCCESS = `${DEFAULT}MOVE_NODE_SUCCESS`;
export const MOVE_NODE_FAILURE = `${DEFAULT}MOVE_NODE_FAILURE`;
