/*
 *
 * TalkWrapper constants
 *
 */

const DEFAULT = 'app/TalkWrapper/';

export const ADD_TALK_WRAPPERS = `${DEFAULT}ADD_TALK_WRAPPERS`;
export const ADDING_TALK_WRAPPERS = `${DEFAULT}ADDING_TALK_WRAPPERS`;
export const ADD_TALK_WRAPPERS_SUCCESS = `${DEFAULT}ADD_TALK_WRAPPERS_SUCCESS`;
export const ADD_TALK_WRAPPERS_FAILURE = `${DEFAULT}ADD_TALK_WRAPPERS_FAILURE`;

export const UPDATE_TALK_WRAPPERS = `${DEFAULT}UPDATE_TALK_WRAPPERS`;
export const UPDATING_TALK_WRAPPERS = `${DEFAULT}UPDATING_TALK_WRAPPERS`;
export const UPDATE_TALK_WRAPPERS_SUCCESS = `${DEFAULT}UPDATE_TALK_WRAPPERS_SUCCESS`;
export const UPDATE_TALK_WRAPPERS_FAILURE = `${DEFAULT}UPDATE_TALK_WRAPPERS_FAILURE`;

export const DELETE_TALK_WRAPPERS = `${DEFAULT}DELETE_TALK_WRAPPERS`;
export const DELETING_TALK_WRAPPERS = `${DEFAULT}DELETING_TALK_WRAPPERS`;
export const DELETE_TALK_WRAPPERS_SUCCESS = `${DEFAULT}DELETE_TALK_WRAPPERS_SUCCESS`;
export const DELETE_TALK_WRAPPERS_FAILURE = `${DEFAULT}DELETE_TALK_WRAPPERS_FAILURE`;
