/*
 *
 * TalkWrapper constants
 *
 */

const DEFAULT = 'app/TalkWrapper/';

export const ADD_TALK_WRAPPERS = `${DEFAULT}ADD_TALK_WRAPPERS`;
export const ADDING_TALK_WRAPPERS = `${DEFAULT}ADDING_TALK_WRAPPERS`;
export const ADD_TALK_WRAPPERS_SUCCESS = `${DEFAULT}ADD_TALK_WRAPPERS_SUCCESS`;
export const ADD_TALK_WRAPPERS_FAILURE = `${DEFAULT}ADD_TALK_WRAPPERS_FAILURE`;
