/*
 *
 * NodeWrapper constants
 *
 */

const DEFAULT = 'app/NodeWrapper/';

export const ADD_NODE_WRAPPERS = `${DEFAULT}ADD_NODE_WRAPPERS`;
export const ADDING_NODE_WRAPPERS = `${DEFAULT}ADDING_NODE_WRAPPERS`;
export const ADD_NODE_WRAPPERS_SUCCESS = `${DEFAULT}ADD_NODE_WRAPPERS_SUCCESS`;
export const ADD_NODE_WRAPPERS_FAILURE = `${DEFAULT}ADD_NODE_WRAPPERS_FAILURE`;

export const GET_NODE_WRAPPERS = `${DEFAULT}GET_NODE_WRAPPERS`;
export const GETTING_NODE_WRAPPERS = `${DEFAULT}GETTING_NODE_WRAPPERS`;
export const GET_NODE_WRAPPERS_SUCCESS = `${DEFAULT}GET_NODE_WRAPPERS_SUCCESS`;
export const GET_NODE_WRAPPERS_FAILURE = `${DEFAULT}GET_NODE_WRAPPERS_FAILURE`;
