/*
 *
 * Permissions constants
 *
 */

export const DEFAULT = 'Permissions/';

export const GET_PERMISSIONS = `${DEFAULT}GET_PERMISSIONS`;
export const GETTING_PERMISSIONS = `${DEFAULT}GETTING_PERMISSIONS`;
export const GET_PERMISSIONS_SUCCESS = `${DEFAULT}GET_PERMISSIONS_SUCCESS`;
export const GET_PERMISSIONS_FAILURE = `${DEFAULT}GET_PERMISSIONS_FAILURE`;

export const SET_PERMISSIONS = `${DEFAULT}SET_PERMISSIONS`;
export const SETTING_PERMISSIONS = `${DEFAULT}SETTING_PERMISSIONS`;
export const SET_PERMISSIONS_SUCCESS = `${DEFAULT}SET_PERMISSIONS_SUCCESS`;
export const SET_PERMISSIONS_FAILURE = `${DEFAULT}SET_PERMISSIONS_FAILURE`;

export const SET_USER = `${DEFAULT}SET_USER`;
export const SET_USER_SUCCESS = `${DEFAULT}SET_USER_SUCCESS`;
export const SET_USER_FAILURE = `${DEFAULT}SET_USER_FAILURE`;
