/*
 *
 * Talk constants
 *
 */

export const DEFAULT_ACTION = 'app/Talk';
export const LOAD_PARENTS = `${DEFAULT_ACTION}/LOAD_PARENTS`;
export const REQUESTING_PARENTS = `${DEFAULT_ACTION}/REQUESTING_PARENTS`;
export const REQUESTING_PARENTS_SUCCESS = `${DEFAULT_ACTION}/REQUESTING_PARENTS_SUCCESS`;
export const REQUESTING_PARENTS_FAILURE = `${DEFAULT_ACTION}/REQUESTING_PARENTS_FAILURE`;

export const ADD_NODE = `${DEFAULT_ACTION}/ADD_NODE`;
export const ADDING_NODE = `${DEFAULT_ACTION}/ADDING_NODE`;
export const ADD_NODE_SUCCESS = `${DEFAULT_ACTION}/ADD_NODE_SUCCESS`;
export const ADD_NODE_FAILURE = `${DEFAULT_ACTION}/ADD_NODE_FAILURE`;
