/*
 *
 * Expression constants
 *
 */

export const DEFAULT = 'app/Expression/';

export const SET_INTENT_NAME = `${DEFAULT}SET_INTENT_NAME`;
export const UPDATE_INTENT_NAME = `${DEFAULT}UPDATE_INTENT_NAME`;

export const SAVE_UPDATED_INTENT_NAME = `${DEFAULT}SAVE_UPDATED_INTENT_NAME`;
export const SAVING_UPDATED_INTENT_NAME = `${DEFAULT}SAVING_UPDATED_INTENT_NAME`;

export const GET_EXPRESSION = `${DEFAULT}GET_EXPRESSION`;
export const GETING_EXPRESSION = `${DEFAULT}GETING_EXPRESSION`;
export const GET_EXPRESSION_SUCCESS = `${DEFAULT}GET_EXPRESSION_SUCCESS`;
export const GET_EXPRESSION_FAILURE = `${DEFAULT}GET_EXPRESSION_FAILURE`;

export const ADD_EXPRESSION = `${DEFAULT}ADD_EXPRESSION`;
export const ADDING_EXPRESSION = `${DEFAULT}ADDING_EXPRESSION`;
export const ADD_EXPRESSION_SUCCESS = `${DEFAULT}ADD_EXPRESSION_SUCCESS`;
export const ADD_EXPRESSION_FAILURE = `${DEFAULT}ADD_EXPRESSION_FAILURE`;

export const REMOVE_EXPRESSION = `${DEFAULT}REMOVE_EXPRESSION`;
export const REMOVING_EXPRESSION = `${DEFAULT}REMOVING_EXPRESSION`;
export const REMOVE_EXPRESSION_SUCCESS = `${DEFAULT}REMOVE_EXPRESSION_SUCCESS`;
export const REMOVE_EXPRESSION_FAILURE = `${DEFAULT}REMOVE_EXPRESSION_FAILURE`;

export const ADD_PARAMETER = `${DEFAULT}ADD_PARAMETER`;
export const ADDING_PARAMETER = `${DEFAULT}ADDING_PARAMETER`;
export const ADD_PARAMETER_SUCCESS = `${DEFAULT}ADD_PARAMETER_SUCCESS`;
export const ADD_PARAMETER_FAILURE = `${DEFAULT}ADD_PARAMETER_FAILURE`;

export const REMOVE_PARAMETER = `${DEFAULT}REMOVE_X_ENTITY`;
export const REMOVING_PARAMETER = `${DEFAULT}REMOVING_PARAMETER`;
export const REMOVE_PARAMETER_SUCCESS = `${DEFAULT}REMOVE_PARAMETER_SUCCESS`;
export const REMOVE_PARAMETER_FAILURE = `${DEFAULT}REMOVE_PARAMETER_FAILURE`;

export const GET_ENTITIES = `${DEFAULT}GET_ENTITIES`;
export const GETTING_ENTITIES = `${DEFAULT}GETTING_ENTITIES`;
export const GET_ENTITIES_SUCCESS = `${DEFAULT}GET_ENTITIES_SUCCESS`;
export const GET_ENTITIES_FAILURE = `${DEFAULT}GET_ENTITIES_FAILURE`;
