/*
 *
 * Chatbot constants
 *
 */

export const DEFAULT = 'Chatbot/';

export const UPDATE_INPUT = `${DEFAULT}UPDATE_INPUT`;
export const CLEAR_INPUT = `${DEFAULT}CLEAR_INPUT`;
export const SET_TALKWRAPPER = `${DEFAULT}SET_TALKWRAPPER`;

export const SEND_INPUT = `${DEFAULT}SEND_INPUT`;
export const SENDING_INPUT = `${DEFAULT}SENDING_INPUT`;
export const SEND_INPUT_SUCCESS = `${DEFAULT}SEND_INPUT_SUCCESS`;
export const SEND_INPUT_FAILURE = `${DEFAULT}SEND_INPUT_FAILURE`;

export const ADD_MESSAGE = `${DEFAULT}ADD_MESSAGE_PENDING`;
export const MESSAGE_SUCCESS = `${DEFAULT}MESSAGE_SUCCESS`;
export const MESSAGE_FAILURE = `${DEFAULT}MESSAGE_FAILURE`;

export const ADD_MESSAGE_HUMAN = `${DEFAULT}ADD_MESSAGE_HUMAN`;
export const ADD_MESSAGE_BOT = `${DEFAULT}ADD_MESSAGE_BOT`;

export const RESET = `${DEFAULT}RESET`;
