/*
 *
 * Entities constants
 *
 */

export const DEFAULT = 'Entities';

export const GET_ENTITIES = `${DEFAULT}/GET_ENTITIES`;
export const GETING_ENTITIES = `${DEFAULT}/GETING_ENTITIES`;
export const GET_ENTITIES_SUCCESS = `${DEFAULT}/GET_ENTITIES_SUCCESS`;
export const GET_ENTITIES_FAILURE = `${DEFAULT}/GET_ENTITIES_FAILURE`;

export const REMOVE_ENTITIES = `${DEFAULT}/REMOVE_ENTITIES`;
export const REMOVING_ENTITIES = `${DEFAULT}/REMOVING_ENTITIES`;
export const REMOVE_ENTITIES_SUCCESS = `${DEFAULT}/REMOVE_ENTITIES_SUCCESS`;
export const REMOVE_ENTITIES_FAILURE = `${DEFAULT}/REMOVE_ENTITIES_FAILURE`;

export const ADD_ENTITY = `${DEFAULT}/ADD_ENTITY`;
export const ADDING_ENTITY = `${DEFAULT}/ADDING_ENTITY`;
export const ADD_ENTITY_SUCCESS = `${DEFAULT}/ADD_ENTITY_SUCCESS`;
export const ADD_ENTITY_FAILURE = `${DEFAULT}/ADD_ENTITY_FAILURE`;
