/*
 *
 * EditNode constants
 *
 */

export const DEFAULT = 'EditNode/';

export const LOAD_NODE = `${DEFAULT}LOAD_NODE`;
export const LOADING_NODE_INFO = `${DEFAULT}LOADING_NODE_INFO`;
export const LOAD_NODE_INFO_SUCCESS = `${DEFAULT}LOAD_NODE_INFO_SUCCESS`;
export const LOAD_NODE_INFO_FAILURE = `${DEFAULT}LOAD_NODE_INFO_FAILURE`;

export const SAVE_NODE = `${DEFAULT}SAVE_NODE`;
export const SAVING_NODE_INFO = `${DEFAULT}SAVING_NODE_INFO`;
export const SAVE_NODE_INFO_SUCCESS = `${DEFAULT}SAVE_NODE_INFO_SUCCESS`;
export const SAVE_NODE_INFO_FAILURE = `${DEFAULT}SAVE_NODE_INFO_FAILURE`;
