/*
 *
 * IntentPage constants
 *
 */

export const DEFAULT = 'app/IntentPage/';

export const GET_AGENT = `${DEFAULT}GET_AGENT`;
export const GETTING_AGENT = `${DEFAULT}GETTING_AGENT`;
export const GET_AGENT_SUCCESS = `${DEFAULT}GET_AGENT_SUCCESS`;
export const GET_AGENT_FAILURE = `${DEFAULT}GET_AGENT_FAILURE`;

export const ADD_INTENT = `${DEFAULT}ADD_INTENT`;
export const ADDING_INTENT = `${DEFAULT}ADDING_INTENT`;
export const ADD_INTENT_SUCCESS = `${DEFAULT}ADD_INTENT_SUCCESS`;
export const ADD_INTENT_FAILURE = `${DEFAULT}ADD_INTENT_FAILURE`;

export const REMOVE_INTENTS = `${DEFAULT}REMOVE_INTENTS`;
export const REMOVING_INTENTS = `${DEFAULT}REMOVING_INTENTS`;
export const REMOVE_INTENTS_SUCCESS = `${DEFAULT}REMOVE_INTENTS_SUCCESS`;
export const REMOVE_INTENTS_FAILURE = `${DEFAULT}REMOVE_INTENTS_FAILURE`;
