/*
 *
 * Training constants
 *
 */

export const DEFAULT = 'Training/';

export const GET_JSON = `${DEFAULT}GET_JSON`;
export const GETTING_JSON = `${DEFAULT}GETTING_JSON`;
export const GETTING_JSON_SUCCESS = `${DEFAULT}GETTING_JSON_SUCCESS`;
export const GETTING_JSON_FAILURE = `${DEFAULT}GETTING_JSON_FAILURE`;

export const GET_ALL = `${DEFAULT}GET_ALL`;
export const GETTING_ALL = `${DEFAULT}GETTING_ALL`;
export const GET_ALL_SUCCESS = `${DEFAULT}GET_ALL_SUCCESS`;
export const GET_ALL_FAILURE = `${DEFAULT}GET_ALL_FAILURE`;

export const VIEW_JSON = `${DEFAULT}VIEW_JSON`;
export const GENERATING_JSON = `${DEFAULT}VIEWING_JSON`;
export const VIEW_JSON_SUCCESS = `${DEFAULT}VIEW_JSON_SUCCESS`;
export const VIEW_JSON_FAILURE = `${DEFAULT}VIEW_JSON_FAILURE`;

export const TRAIN_JSON = `${DEFAULT}TRAIN_JSON`;
export const TRAINING_JSON = `${DEFAULT}TRAINING_JSON`;
export const TRAIN_JSON_SUCCESS = `${DEFAULT}TRAIN_JSON_SUCCESS`;
export const TRAIN_JSON_FAILURE = `${DEFAULT}TRAIN_JSON_FAILURE`;

export const GET_STATUS = `${DEFAULT}GET_STATUS`;
export const GETTING_STATUS = `${DEFAULT}GETTING_STATUS`;
export const GET_STATUS_SUCCESS = `${DEFAULT}GET_STATUS_SUCCESS`;
export const GET_STATUS_FAILURE = `${DEFAULT}GET_STATUS_FAILURE`;
export const START_WATCH = `${DEFAULT}START_WATCH`;
export const POLL_STOP = `${DEFAULT}POLL_STOP`;
